### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [glostis/venv-wrapper#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  [choosealicense.com](https://choosealicense.com) is a good resource to help you choose an appropriate one.

**Comment by glostis** [comment]
Hi @unixorn !
Sorry for replying so late, somehow I didn't get the notification for your issue...
I've added a license and a readme file to this repo to make it a bit more usable by someone else.

Thanks!

**Comment by unixorn** [comment]
Thanks for making the updates! You're in the list :-)
