### ISSUE TITLE
mkvenv doesn't allow me to create a venv - asks me to deactivate first

### ISSUE THREAD

**Issue by RaddishIoW** [glostis/venv-wrapper#2]
OS: macOS Mojave 10.14.6
Oh-my-zsh on iTerm

When running mkvenv, venv-wrapper returns with the message:
`You must first deactivate your current virtual environment before creating a new one,
by typing: 'deactivate'`

I have no active venv - there is no venv to deactivate.

Looking  at the script, the output of
`python -c "import sys; import os; assert hasattr(sys, 'base_prefix'); print(os.path.basename(sys.prefix))" 2> /dev/null`
is `3.8.2` on my system. I'm guessing this is the result of `print(os.path.basename(sys.prefix)`.
Because it returns this, it thinks I have a venv already active...

**Comment by glostis** [comment]
Hi @RaddishIoW,

Thanks for opening up the issue and sorry for replying late, for some reason I did not have notifications enabled for this repo...

I have to admit that the 
```
python -c "import sys; import os; assert hasattr(sys, 'base_prefix'); print(os.path.basename(sys.prefix))" 2> /dev/null
```
line to figure out if you are currently in a virtual environment is a dirty hack that worked on my two installs (macOS and Ubuntu), but it doesn't surprise me that it is not generic enough.

Judging from [this SO answer](https://stackoverflow.com/a/58026969/9977650), there seems to be a more robust way to do this by checking if `sys.base_prefix != sys.prefix`.

It seems to work on my machine, so I'll push a commit to `master` with this change.

**Comment by glostis** [comment]
Pushed to `master` in https://github.com/glostis/venv-wrapper/commit/81af4239bc5bb99eaa98117b2988a29fdd5b7eb7

@RaddishIoW would you mind sourcing the new version of the plugin and letting me know if it solves the issue?
